### ISSUE TITLE
9. Command History

### ISSUE THREAD

**Issue by marco-garzon-lara** [The-Spaghetti-Is-Ready/ICT374-Assignment2-2024#10]
The shell remembers the commands entered into the shell and the user can select one of the previous commands by the Up Arrow key and Down Arrow key. 

The user can also display the past commands using shell built-in command history and repeat a previous command using the special character `!` followed by the command number, eg, `!12`, which would repeat the 12th command. 

The shell can also repeat the last command that starts with a string using `!string`.

**Comment by Minywire** [comment]
Stack implementation in lab 5
