### ISSUE TITLE
Make a Command History Stack

### ISSUE THREAD

**Issue by marco-garzon-lara** [The-Spaghetti-Is-Ready/ICT374-Assignment2-2024#17]
# Problem

We need a first-in last-out command history system which allows user to easily cycle their input commands from most-recent to least-recent. Currently in branch `2-Reconfigurable-Shell-Prompt` the command history is implemented as an array, but this should be enhanced to have stack-like behaviour.

**Comment by Minywire** [comment]
Lab 5 goes over string stack
