### ISSUE TITLE
4. Wildcard Characters

### ISSUE THREAD

**Issue by marco-garzon-lara** [The-Spaghetti-Is-Ready/ICT374-Assignment2-2024#5]
If a token contains wildcard characters `*` or `?`, the token is treated as a filename. The wildcard characters in such a token indicate to the shell that the filename must be expanded. For example the command:

`% ls *.c`

may be expanded to ls `ex1.c ex2.c ex3.c` if there are three matching files 'ex1.c ex2.c ex3.c' in the current directory.

You may implement this feature using the C function `glob`.

**Comment by Minywire** [comment]
[glob()](https://www.man7.org/linux/man-pages/man3/glob.3.html)
