### ISSUE TITLE
7. Background Job Execution

### ISSUE THREAD

**Issue by marco-garzon-lara** [The-Spaghetti-Is-Ready/ICT374-Assignment2-2024#8]
For example:

`% xterm &`

The commannd line starts the command `xterm` in the background (i.e., the shell will not wait for the process to terminate and you can type in the next command immediately). The following command line

`% sleep 20 &  ps -l`

starts the command sleep 20 and immediately execute the command `ps -l` without waiting for the command sleep 20 to finish first.

**Comment by Minywire** [comment]
Topic 4 (possibly with WNOHANG)
